// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQxltUaYcGQzJANd1ZKQHsNDeuyeRfEB4',
    appId: '1:103333110508:web:c69de4d2c8715743d4fbc9',
    messagingSenderId: '103333110508',
    projectId: 'women-safety-app-73a92',
    authDomain: 'women-safety-app-73a92.firebaseapp.com',
    storageBucket: 'women-safety-app-73a92.firebasestorage.app',
    measurementId: 'G-B329ZT0M8G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVGlO5jM5Otr-upe8BJ7IHTV3ssJJMBzs',
    appId: '1:103333110508:android:50f208b50146d546d4fbc9',
    messagingSenderId: '103333110508',
    projectId: 'women-safety-app-73a92',
    storageBucket: 'women-safety-app-73a92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS3boXdTLqkBv-12y33ZIslOL5DecSz8Q',
    appId: '1:103333110508:ios:f3bf24eeb2707be8d4fbc9',
    messagingSenderId: '103333110508',
    projectId: 'women-safety-app-73a92',
    storageBucket: 'women-safety-app-73a92.firebasestorage.app',
    iosClientId: '103333110508-pkmdtnhnli7do0puauogbgjqbfukp08l.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS3boXdTLqkBv-12y33ZIslOL5DecSz8Q',
    appId: '1:103333110508:ios:f3bf24eeb2707be8d4fbc9',
    messagingSenderId: '103333110508',
    projectId: 'women-safety-app-73a92',
    storageBucket: 'women-safety-app-73a92.firebasestorage.app',
    iosClientId: '103333110508-pkmdtnhnli7do0puauogbgjqbfukp08l.apps.googleusercontent.com',
    iosBundleId: 'com.example.womenSafetyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQxltUaYcGQzJANd1ZKQHsNDeuyeRfEB4',
    appId: '1:103333110508:web:345882cb1a3f0866d4fbc9',
    messagingSenderId: '103333110508',
    projectId: 'women-safety-app-73a92',
    authDomain: 'women-safety-app-73a92.firebaseapp.com',
    storageBucket: 'women-safety-app-73a92.firebasestorage.app',
    measurementId: 'G-NBRRFG9MFZ',
  );
}
